"""add make column to car

Revision ID: a10b316f0445
Revises: f78f9a8698a2
Create Date: 2025-10-20 09:40:34.881176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a10b316f0445'
down_revision: Union[str, Sequence[str], None] = 'f78f9a8698a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('Car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['dbo.Owner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.add_column(
        'Car',
        sa.Column('make', sa.String(32), nullable=True),
        schema='dbo'
    )
    op.create_index(op.f('ix_dbo_Car_vin'), 'Car', ['vin'], unique=True, schema='dbo')
    op.create_table('Claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['dbo.Car.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_index('ix_claim_car_date', 'Claim', ['car_id', 'claim_date'], unique=False, schema='dbo')
    op.create_table('Insurance_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('logged_expiry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['dbo.Car.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_index('ix_policy_car_dates', 'Insurance_policy', ['car_id', 'start_date', 'end_date'], unique=False, schema='dbo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policy_car_dates', table_name='Insurance_policy', schema='dbo')
    op.drop_table('Insurance_policy', schema='dbo')
    op.drop_index('ix_claim_car_date', table_name='Claim', schema='dbo')
    op.drop_table('Claim', schema='dbo')
    op.drop_index(op.f('ix_dbo_Car_vin'), table_name='Car', schema='dbo')
    op.drop_table('Car', schema='dbo')
    op.drop_table('Owner', schema='dbo')
    # ### end Alembic commands ###
