"""errors

Revision ID: a5ad8660847b
Revises: a10b316f0445
Create Date: 2025-10-20 10:17:07.551329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ad8660847b'
down_revision: Union[str, Sequence[str], None] = 'a10b316f0445'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('owner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vin', sa.String(length=32), nullable=False),
    sa.Column('make', sa.String(length=32), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('year_of_manufacture', sa.Integer(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['dbo.owner.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_index(op.f('ix_dbo_car_vin'), 'car', ['vin'], unique=True, schema='dbo')
    op.create_table('claim',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('claim_date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['dbo.car.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_index('ix_claim_car_date', 'claim', ['car_id', 'claim_date'], unique=False, schema='dbo')
    op.create_table('insurance_policy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('logged_expiry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['dbo.car.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='dbo'
    )
    op.create_index('ix_policy_car_dates', 'insurance_policy', ['car_id', 'start_date', 'end_date'], unique=False, schema='dbo')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_policy_car_dates', table_name='insurance_policy', schema='dbo')
    op.drop_table('insurance_policy', schema='dbo')
    op.drop_index('ix_claim_car_date', table_name='claim', schema='dbo')
    op.drop_table('claim', schema='dbo')
    op.drop_index(op.f('ix_dbo_car_vin'), table_name='car', schema='dbo')
    op.drop_table('car', schema='dbo')
    op.drop_table('owner', schema='dbo')
    # ### end Alembic commands ###
